/*
 * This source file was generated by the Gradle 'init' task
 */
package youspace;

import javafx.application.Application;
import javafx.stage.Stage;
import youspace.database.DatabaseInitializer;

public class App extends Application {

    @Override
    public void start(Stage stage) {
        DatabaseInitializer.initialize();
        stage.setTitle("YouSpace");
        stage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}